appname: "App-SquidArm-Web"
layout: "main"
charset: "UTF-8"
template: "simple"
environment: "development"
sarm_conf: "sarm.conf"
plack_middlewares:
    -
        - ConditionalGET
    -
        - ETag
